"use client";

import { useEffect, useRef, useState } from "react";
import {
  X, ChevronRight, ChevronLeft, Loader2, Printer,
  MapPin, Users, Clock, Calendar, AlertTriangle, Building2,
  CloudSun, FileText, Check,
} from "lucide-react";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";
import {
  getCrewContacts, getProjectLocations, getShotLists, getProfile,
} from "@/lib/supabase/queries";
import type { Project, CrewContact, ProjectLocation, ShotListItem } from "@/types";

// ─── Types ────────────────────────────────────────────────────────────────────

interface CrewWithCall extends CrewContact { callTime: string }
interface LocationWithParking extends ProjectLocation { parkingNotes: string }
interface ScheduleItem {
  time: string;
  label: string;
  location: string | null;
  type: "logistics" | "setup" | "shoot" | "break" | "move" | "wrap";
}
interface GeneratedSheet {
  schedule: ScheduleItem[];
  warning: string | null;
}
interface FormData {
  shootDate: string;
  callTime: string;
  wrapTime: string;
  hospital: string;
  weather: string;
  confidential: boolean;
  directorNote: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const DEPT_ORDER = [
  "Production", "Direction", "Camera", "Lighting", "Grip", "Sound",
  "Art", "Wardrobe", "Hair & Makeup", "Talent", "Other",
];

function groupByDept(crew: CrewWithCall[]) {
  const map = new Map<string, CrewWithCall[]>();
  for (const m of crew) {
    const dept = m.department || "Other";
    if (!map.has(dept)) map.set(dept, []);
    map.get(dept)!.push(m);
  }
  const sorted = new Map<string, CrewWithCall[]>();
  for (const d of DEPT_ORDER) if (map.has(d)) sorted.set(d, map.get(d)!);
  for (const [d, v] of map) if (!sorted.has(d)) sorted.set(d, v);
  return sorted;
}

const TYPE_STYLE: Record<ScheduleItem["type"], string> = {
  logistics: "border-l-[#d4a853]/60 bg-[#d4a853]/5 text-[#d4a853]",
  setup:     "border-l-blue-400/60 bg-blue-400/5 text-blue-400",
  shoot:     "border-l-emerald-400/60 bg-emerald-400/5 text-emerald-400",
  break:     "border-l-purple-400/60 bg-purple-400/5 text-purple-400",
  move:      "border-l-amber-400/60 bg-amber-400/5 text-amber-400",
  wrap:      "border-l-muted-foreground/40 bg-muted/30 text-muted-foreground",
};
const TYPE_LABEL: Record<ScheduleItem["type"], string> = {
  logistics: "LOGISTICS", setup: "SETUP", shoot: "SHOOT",
  break: "BREAK", move: "MOVE", wrap: "WRAP",
};

// ─── Print Sheet ──────────────────────────────────────────────────────────────

function PrintSheet({
  project, profile, formData, crew, locations, sheet,
}: {
  project: Project;
  profile: { business_name?: string; logo_url?: string; first_name?: string; last_name?: string } | null;
  formData: FormData;
  crew: CrewWithCall[];
  locations: LocationWithParking[];
  sheet: GeneratedSheet;
}) {
  const deptMap = groupByDept(crew);
  const producerName = profile
    ? [profile.first_name, profile.last_name].filter(Boolean).join(" ")
    : "";

  return (
    <div id="print-sheet" className="bg-white text-black font-sans text-sm print:text-[11px]">
      {/* Header */}
      <div className="border-b-2 border-black pb-3 mb-4 flex items-start justify-between gap-4">
        <div>
          {profile?.logo_url && (
            <img src={profile.logo_url} alt="Logo" className="h-10 object-contain mb-1" />
          )}
          <p className="font-bold text-base">{profile?.business_name || "Production Company"}</p>
        </div>
        <div className="text-center flex-1">
          <h1 className="font-black text-xl uppercase tracking-wide">{project.title}</h1>
          {project.client_name && (
            <p className="text-xs text-gray-600">Client: {project.client_name}</p>
          )}
          <p className="text-xs font-semibold mt-0.5">
            CALL SHEET — {formData.shootDate
              ? new Date(formData.shootDate + "T12:00:00").toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })
              : "Date TBD"}
          </p>
        </div>
        <div className="text-right text-xs">
          {formData.confidential && (
            <span className="inline-block border border-black px-2 py-0.5 text-[10px] font-bold tracking-widest mb-1">CONFIDENTIAL</span>
          )}
          {producerName && <p className="font-medium">{producerName}</p>}
          <p className="text-gray-500">Generated by Cineflow</p>
        </div>
      </div>

      {/* Info strip */}
      <div className="grid grid-cols-4 gap-2 mb-4 text-xs">
        {[
          { label: "General Call", value: formData.callTime || "TBD" },
          { label: "Wrap", value: formData.wrapTime || "TBD" },
          { label: "Weather", value: formData.weather || "—" },
          { label: "Nearest Hospital", value: formData.hospital || "See location contact" },
        ].map(({ label, value }) => (
          <div key={label} className="border border-gray-300 rounded p-2">
            <p className="font-bold uppercase text-[9px] text-gray-500 mb-0.5">{label}</p>
            <p className="font-semibold">{value}</p>
          </div>
        ))}
      </div>

      {/* Warning */}
      {sheet.warning && (
        <div className="mb-4 border border-amber-400 bg-amber-50 rounded p-2 text-xs text-amber-800 flex gap-2">
          <span className="font-bold">⚠ NOTE:</span> {sheet.warning}
        </div>
      )}

      {/* Locations */}
      {locations.length > 0 && (
        <div className="mb-4">
          <h2 className="font-black uppercase text-[10px] tracking-widest border-b border-gray-300 pb-1 mb-2">Locations</h2>
          <div className="grid grid-cols-2 gap-2">
            {locations.map((loc) => (
              <div key={loc.id} className="border border-gray-200 rounded p-2 text-xs">
                <p className="font-bold">{loc.name}</p>
                {loc.address && <p className="text-gray-600">{loc.address}</p>}
                {loc.parkingNotes && <p className="text-gray-600">Parking: {loc.parkingNotes}</p>}
                {loc.contact_name && (
                  <p className="text-gray-600">Contact: {loc.contact_name}{loc.contact_phone ? ` · ${loc.contact_phone}` : ""}</p>
                )}
                {loc.maps_url && (
                  <a href={loc.maps_url} className="text-blue-600 underline">Maps →</a>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Shooting Schedule */}
      <div className="mb-4">
        <h2 className="font-black uppercase text-[10px] tracking-widest border-b border-gray-300 pb-1 mb-2">Shooting Schedule</h2>
        <table className="w-full text-xs border-collapse">
          <thead>
            <tr className="bg-gray-100">
              <th className="border border-gray-200 px-2 py-1 text-left font-bold w-16">Time</th>
              <th className="border border-gray-200 px-2 py-1 text-left font-bold w-16">Type</th>
              <th className="border border-gray-200 px-2 py-1 text-left font-bold">Description</th>
              <th className="border border-gray-200 px-2 py-1 text-left font-bold w-28">Location</th>
            </tr>
          </thead>
          <tbody>
            {sheet.schedule.map((item, i) => (
              <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}>
                <td className="border border-gray-200 px-2 py-1 font-mono font-bold whitespace-nowrap">{item.time}</td>
                <td className="border border-gray-200 px-2 py-1 text-[9px] font-bold uppercase text-gray-500">{TYPE_LABEL[item.type]}</td>
                <td className="border border-gray-200 px-2 py-1">{item.label}</td>
                <td className="border border-gray-200 px-2 py-1 text-gray-600">{item.location || "—"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Crew by Department */}
      {crew.length > 0 && (
        <div className="mb-4">
          <h2 className="font-black uppercase text-[10px] tracking-widest border-b border-gray-300 pb-1 mb-2">Crew</h2>
          <div className="grid grid-cols-2 gap-3">
            {Array.from(deptMap.entries()).map(([dept, members]) => (
              <div key={dept}>
                <p className="font-bold text-[10px] uppercase text-gray-500 mb-1">{dept}</p>
                <table className="w-full text-xs border-collapse">
                  <tbody>
                    {members.map((m) => (
                      <tr key={m.id} className="border-b border-gray-100">
                        <td className="py-0.5 font-medium w-28">{m.name}</td>
                        <td className="py-0.5 text-gray-600 w-24">{m.role}</td>
                        <td className="py-0.5 font-mono font-bold text-right">{m.callTime || formData.callTime || "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Director's Note */}
      {formData.directorNote && (
        <div className="mb-4 border border-gray-200 rounded p-3">
          <p className="font-black uppercase text-[10px] tracking-widest text-gray-500 mb-1">Director's Note</p>
          <p className="text-xs leading-relaxed">{formData.directorNote}</p>
        </div>
      )}

      <div className="border-t border-gray-200 pt-2 text-[9px] text-gray-400 text-center print:mt-auto">
        Generated with Cineflow · {new Date().toLocaleDateString()}
        {formData.confidential && " · CONFIDENTIAL — Do not distribute"}
      </div>
    </div>
  );
}

// ─── Step indicator ───────────────────────────────────────────────────────────

function StepDot({ n, current }: { n: number; current: number }) {
  const done = current > n;
  const active = current === n;
  return (
    <div className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-bold transition-all
      ${done ? "bg-emerald-500 text-white" : active ? "bg-[#d4a853] text-black" : "bg-muted text-muted-foreground"}`}>
      {done ? <Check className="h-3 w-3" /> : n}
    </div>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export function CallSheetGenerator({ project, onClose }: { project: Project; onClose: () => void }) {
  const [step, setStep] = useState<1 | 2 | 3 | 4 | 5>(1);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [sheet, setSheet] = useState<GeneratedSheet | null>(null);

  const [profile, setProfile] = useState<any>(null);
  const [crew, setCrew] = useState<CrewWithCall[]>([]);
  const [locations, setLocations] = useState<LocationWithParking[]>([]);
  const [shotItems, setShotItems] = useState<ShotListItem[]>([]);

  const [formData, setFormData] = useState<FormData>({
    shootDate: "",
    callTime: "07:00",
    wrapTime: "19:00",
    hospital: "",
    weather: "",
    confidential: false,
    directorNote: "",
  });

  const printRef = useRef<HTMLDivElement>(null);

  // Load all project data on mount
  useEffect(() => {
    async function load() {
      try {
        const [crewData, locData, shotListData, profileData] = await Promise.all([
          getCrewContacts(project.id),
          getProjectLocations(project.id),
          getShotLists(project.id),
          getProfile(),
        ]);
        setCrew(crewData.map((c) => ({ ...c, callTime: "" })));
        setLocations(locData.map((l) => ({ ...l, parkingNotes: "" })));
        const items = (shotListData[0] as any)?.shot_list_items ?? (shotListData[0] as any)?.items ?? [];
        setShotItems(items);
        setProfile(profileData);
      } catch {
        toast.error("Failed to load project data");
      } finally {
        setLoading(false);
      }
    }
    load();
  }, [project.id]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const res = await fetch("/api/call-sheet/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ project, shotItems, crew, locations, formData }),
      });
      if (!res.ok) throw new Error("Generation failed");
      const data = await res.json();
      setSheet(data);
      setStep(5);
    } catch {
      toast.error("Failed to generate schedule — try again");
    } finally {
      setGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm">
        <div className="flex flex-col items-center gap-3 text-foreground">
          <Loader2 className="h-8 w-8 animate-spin text-[#d4a853]" />
          <p className="text-sm text-muted-foreground">Loading project data…</p>
        </div>
      </div>
    );
  }

  return (
    <>
      {/* Print styles */}
      <style>{`
        @media print {
          body > * { display: none !important; }
          #call-sheet-print-portal { display: block !important; position: static !important; }
          #print-sheet { display: block !important; padding: 24px; }
          .no-print { display: none !important; }
        }
      `}</style>

      {/* Modal */}
      <div className="no-print fixed inset-0 z-50 flex flex-col bg-background">
        {/* Top bar */}
        <div className="flex shrink-0 items-center justify-between border-b border-border px-6 py-4">
          <div className="flex items-center gap-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#d4a853]/25 bg-[#d4a853]/10">
              <FileText className="h-4 w-4 text-[#d4a853]" />
            </div>
            <div>
              <h2 className="font-display text-sm font-semibold text-foreground">Call Sheet Generator</h2>
              <p className="text-[11px] text-muted-foreground">{project.title}</p>
            </div>
            {/* Step dots */}
            {step < 5 && (
              <div className="ml-4 hidden items-center gap-2 sm:flex">
                {[1, 2, 3, 4].map((n) => (
                  <div key={n} className="flex items-center gap-2">
                    <StepDot n={n} current={step} />
                    {n < 4 && <div className={`h-px w-6 ${step > n ? "bg-emerald-500" : "bg-border"}`} />}
                  </div>
                ))}
              </div>
            )}
          </div>
          <button onClick={onClose} className="rounded-md p-1.5 text-muted-foreground hover:bg-accent hover:text-foreground transition-colors">
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Step content */}
        <div className="flex-1 overflow-y-auto">
          {step === 1 && <Step1 formData={formData} onChange={setFormData} />}
          {step === 2 && <Step2 locations={locations} onChange={setLocations} />}
          {step === 3 && <Step3 crew={crew} formData={formData} onChange={setCrew} />}
          {step === 4 && <Step4 formData={formData} onChange={setFormData} shotCount={shotItems.length} crewCount={crew.length} />}
          {step === 5 && sheet && (
            <div className="mx-auto max-w-4xl px-6 py-6">
              {sheet.warning && (
                <div className="mb-4 flex items-start gap-2 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-400">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                  {sheet.warning}
                </div>
              )}
              <div className="rounded-xl border border-border bg-white shadow-lg">
                <PrintSheet
                  project={project}
                  profile={profile}
                  formData={formData}
                  crew={crew}
                  locations={locations}
                  sheet={sheet}
                />
              </div>
            </div>
          )}
        </div>

        {/* Bottom nav */}
        <div className="no-print shrink-0 flex items-center justify-between border-t border-border px-6 py-4">
          <button
            onClick={step === 1 ? onClose : () => setStep((s) => (s > 1 ? (s - 1) as any : 1))}
            className="flex items-center gap-1.5 rounded-lg border border-border px-4 py-2 text-sm text-muted-foreground hover:bg-accent hover:text-foreground transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
            {step === 1 ? "Cancel" : "Back"}
          </button>

          {step < 4 && (
            <button
              onClick={() => setStep((s) => (s < 4 ? (s + 1) as any : 4))}
              className="flex items-center gap-1.5 rounded-lg bg-[#d4a853] px-5 py-2 text-sm font-bold text-black hover:bg-[#d4a853]/90 transition-colors"
            >
              Next <ChevronRight className="h-4 w-4" />
            </button>
          )}
          {step === 4 && (
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex items-center gap-2 rounded-lg bg-[#d4a853] px-5 py-2 text-sm font-bold text-black hover:bg-[#d4a853]/90 disabled:opacity-50 transition-colors"
            >
              {generating ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</> : "Generate Call Sheet"}
            </button>
          )}
          {step === 5 && (
            <button
              onClick={handlePrint}
              className="flex items-center gap-2 rounded-lg bg-[#d4a853] px-5 py-2 text-sm font-bold text-black hover:bg-[#d4a853]/90 transition-colors"
            >
              <Printer className="h-4 w-4" /> Print / Save PDF
            </button>
          )}
        </div>
      </div>

      {/* Print portal — hidden on screen, visible when printing */}
      <div id="call-sheet-print-portal" style={{ display: "none" }}>
        {sheet && (
          <div id="print-sheet" style={{ padding: 24 }}>
            <PrintSheet
              project={project}
              profile={profile}
              formData={formData}
              crew={crew}
              locations={locations}
              sheet={sheet}
            />
          </div>
        )}
      </div>
    </>
  );
}

// ─── Step 1: Shoot Basics ─────────────────────────────────────────────────────

function Step1({ formData, onChange }: { formData: FormData; onChange: (f: FormData) => void }) {
  const set = (k: keyof FormData, v: any) => onChange({ ...formData, [k]: v });
  return (
    <div className="mx-auto max-w-xl px-6 py-8 space-y-5">
      <div>
        <h3 className="font-display text-base font-semibold text-foreground">Shoot Details</h3>
        <p className="mt-0.5 text-xs text-muted-foreground">Basic info that goes at the top of every call sheet.</p>
      </div>
      <Field label="Shoot Date" required>
        <input type="date" value={formData.shootDate} onChange={(e) => set("shootDate", e.target.value)}
          className="input-style [color-scheme:dark]" />
      </Field>
      <div className="grid grid-cols-2 gap-3">
        <Field label="General Call Time" required>
          <input type="time" value={formData.callTime} onChange={(e) => set("callTime", e.target.value)}
            className="input-style [color-scheme:dark]" />
        </Field>
        <Field label="Wrap Time" required>
          <input type="time" value={formData.wrapTime} onChange={(e) => set("wrapTime", e.target.value)}
            className="input-style [color-scheme:dark]" />
        </Field>
      </div>
      <Field label="Nearest Hospital" hint="Required on professional sets">
        <input placeholder="e.g. Cedars-Sinai Medical Center, 8700 Beverly Blvd" value={formData.hospital}
          onChange={(e) => set("hospital", e.target.value)} className="input-style" />
      </Field>
      <Field label="Weather" hint="Brief description for the crew">
        <input placeholder="e.g. Sunny, 78°F — light breeze expected" value={formData.weather}
          onChange={(e) => set("weather", e.target.value)} className="input-style" />
      </Field>
      <label className="flex cursor-pointer items-center gap-3 rounded-xl border border-border bg-card p-4">
        <input type="checkbox" checked={formData.confidential} onChange={(e) => set("confidential", e.target.checked)}
          className="h-4 w-4 rounded accent-[#d4a853]" />
        <div>
          <p className="text-sm font-medium text-foreground">Mark as Confidential</p>
          <p className="text-xs text-muted-foreground">Adds a CONFIDENTIAL watermark — for NDAs and unreleased work</p>
        </div>
      </label>
    </div>
  );
}

// ─── Step 2: Locations ────────────────────────────────────────────────────────

function Step2({ locations, onChange }: { locations: LocationWithParking[]; onChange: (l: LocationWithParking[]) => void }) {
  return (
    <div className="mx-auto max-w-xl px-6 py-8 space-y-5">
      <div>
        <h3 className="font-display text-base font-semibold text-foreground">Locations</h3>
        <p className="mt-0.5 text-xs text-muted-foreground">Pre-filled from your project. Add parking notes for crew.</p>
      </div>
      {locations.length === 0 && (
        <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
          No locations saved on this project yet — add them in the project's Locations tab.
        </div>
      )}
      {locations.map((loc, i) => (
        <div key={loc.id} className="rounded-xl border border-border bg-card p-4 space-y-3">
          <div className="flex items-start gap-2">
            <MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#d4a853]" />
            <div className="min-w-0">
              <p className="font-medium text-foreground">{loc.name}</p>
              {loc.address && <p className="text-xs text-muted-foreground">{loc.address}</p>}
              {loc.contact_name && <p className="text-xs text-muted-foreground">Contact: {loc.contact_name}{loc.contact_phone ? ` · ${loc.contact_phone}` : ""}</p>}
            </div>
          </div>
          <Field label="Parking notes">
            <input placeholder="e.g. Park in structure B, level 2 — production will validate" value={loc.parkingNotes}
              onChange={(e) => {
                const updated = [...locations];
                updated[i] = { ...updated[i], parkingNotes: e.target.value };
                onChange(updated);
              }}
              className="input-style" />
          </Field>
        </div>
      ))}
    </div>
  );
}

// ─── Step 3: Crew Call Times ──────────────────────────────────────────────────

function Step3({ crew, formData, onChange }: { crew: CrewWithCall[]; formData: FormData; onChange: (c: CrewWithCall[]) => void }) {
  const deptMap = groupByDept(crew);
  return (
    <div className="mx-auto max-w-2xl px-6 py-8 space-y-6">
      <div>
        <h3 className="font-display text-base font-semibold text-foreground">Crew Call Times</h3>
        <p className="mt-0.5 text-xs text-muted-foreground">
          Individual call times default to the general call ({formData.callTime}). Adjust per department or person.
        </p>
      </div>
      {crew.length === 0 && (
        <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
          No crew saved on this project — add them in the project's Crew tab.
        </div>
      )}
      {Array.from(deptMap.entries()).map(([dept, members]) => (
        <div key={dept}>
          <p className="mb-2 text-xs font-bold uppercase tracking-widest text-muted-foreground">{dept}</p>
          <div className="space-y-2">
            {members.map((m) => {
              const idx = crew.findIndex((c) => c.id === m.id);
              return (
                <div key={m.id} className="flex items-center gap-3 rounded-xl border border-border bg-card px-4 py-2.5">
                  <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#d4a853]/10 text-[10px] font-bold text-[#d4a853]">
                    {m.name.charAt(0).toUpperCase()}
                  </div>
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-medium text-foreground">{m.name}</p>
                    <p className="text-xs text-muted-foreground">{m.role}</p>
                  </div>
                  {m.phone && <p className="hidden text-xs text-muted-foreground sm:block">{m.phone}</p>}
                  <input
                    type="time"
                    value={m.callTime || formData.callTime}
                    onChange={(e) => {
                      const updated = [...crew];
                      updated[idx] = { ...updated[idx], callTime: e.target.value };
                      onChange(updated);
                    }}
                    className="w-28 rounded-lg border border-border bg-background px-2 py-1 text-sm font-mono text-foreground [color-scheme:dark] focus:border-[#d4a853]/50 focus:outline-none"
                  />
                </div>
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}

// ─── Step 4: Director's Note + Confirm ───────────────────────────────────────

function Step4({ formData, onChange, shotCount, crewCount }: {
  formData: FormData; onChange: (f: FormData) => void; shotCount: number; crewCount: number;
}) {
  return (
    <div className="mx-auto max-w-xl px-6 py-8 space-y-5">
      <div>
        <h3 className="font-display text-base font-semibold text-foreground">Director's Note</h3>
        <p className="mt-0.5 text-xs text-muted-foreground">A message from the director to the crew. Optional but recommended.</p>
      </div>
      <textarea
        rows={4}
        placeholder="e.g. Today's shoot is all about capturing authentic moments. Prioritize performance over perfection — we'll have time to polish in post. Thank you for your energy and commitment."
        value={formData.directorNote}
        onChange={(e) => onChange({ ...formData, directorNote: e.target.value })}
        className="input-style w-full resize-none"
      />
      <div className="rounded-xl border border-border bg-card p-4 space-y-2">
        <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Ready to generate</p>
        {[
          { icon: Calendar, label: `${formData.shootDate || "No date set"} · ${formData.callTime} → ${formData.wrapTime}` },
          { icon: MapPin, label: `Locations will be pulled from project` },
          { icon: Users, label: `${crewCount} crew member${crewCount !== 1 ? "s" : ""}` },
          { icon: Clock, label: `${shotCount} shot${shotCount !== 1 ? "s" : ""} in shot list — Claude will build the schedule` },
        ].map(({ icon: Icon, label }) => (
          <div key={label} className="flex items-center gap-2 text-sm text-foreground">
            <Icon className="h-4 w-4 shrink-0 text-[#d4a853]" />
            {label}
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── Shared Field wrapper ─────────────────────────────────────────────────────

function Field({ label, hint, required, children }: {
  label: string; hint?: string; required?: boolean; children: React.ReactNode;
}) {
  return (
    <div className="space-y-1.5">
      <label className="flex items-center gap-1 text-xs font-medium text-foreground">
        {label}
        {required && <span className="text-[#d4a853]">*</span>}
        {hint && <span className="ml-1 font-normal text-muted-foreground">— {hint}</span>}
      </label>
      {children}
    </div>
  );
}

