import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const GOLD = "#d4a853";
const DARK = "#0f0f0f";
const BODY = "#1a1a1a";
const MUTED = "#888888";
const BORDER = "#e5e5e5";
const SUBTLE = "#555555";

const base = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.5,
    color: BODY,
    paddingTop: 56,
    paddingBottom: 64,
    paddingHorizontal: 60,
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: DARK,
    marginBottom: 3,
  },
  subtitle: {
    fontSize: 9,
    color: MUTED,
    marginBottom: 1,
  },
  sectionLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 8,
    marginTop: 18,
  },
  sectionLabelFirst: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  body: {
    fontSize: 10,
    lineHeight: 1.7,
    color: BODY,
    marginBottom: 4,
  },
  bullet: {
    flexDirection: "row",
    marginBottom: 6,
  },
  bulletDot: {
    width: 14,
    fontSize: 10,
    color: GOLD,
    fontFamily: "Helvetica-Bold",
  },
  bulletText: {
    flex: 1,
    fontSize: 10,
    lineHeight: 1.5,
    color: BODY,
  },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 60,
    right: 60,
    fontSize: 8,
    color: "#bbbbbb",
    flexDirection: "row",
    justifyContent: "space-between",
  },
});

function stripExt(name: string) {
  return name.replace(/\.[^.]+$/, "");
}

function formatDate() {
  return new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

function PageFooter() {
  return (
    <View style={base.footer} fixed>
      <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
      <Text>CineFlow · usecineflow.com</Text>
    </View>
  );
}

// ── MEETING SUMMARY ───────────────────────────────────────────────────────────

export type MeetingSummaryData = {
  format?: string;
  overview: string;
  topics: string[];
  key_decisions: string[];
  action_items: string[];
  notable_quotes?: { quote: string; speaker?: string | null }[];
};

export function MeetingSummaryPDFDocument({
  filename,
  data,
}: {
  filename: string;
  data: MeetingSummaryData;
}) {
  return (
    <Document>
      <Page size="A4" style={base.page}>
        <View style={base.header}>
          <Text style={base.title}>{stripExt(filename)}</Text>
          <Text style={base.subtitle}>Meeting Summary  ·  {formatDate()}</Text>
          <Text style={base.subtitle}>Generated by CineFlow</Text>
        </View>

        <Text style={base.sectionLabelFirst}>Overview</Text>
        <Text style={base.body}>{data.overview}</Text>

        {data.topics.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Topics Discussed</Text>
            {data.topics.map((topic, i) => (
              <View key={i} style={base.bullet}>
                <Text style={base.bulletDot}>•</Text>
                <Text style={base.bulletText}>{topic}</Text>
              </View>
            ))}
          </View>
        )}

        {data.key_decisions.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Key Decisions</Text>
            {data.key_decisions.map((d, i) => (
              <View key={i} style={base.bullet}>
                <Text style={[base.bulletDot, { color: "#34d399" }]}>✓</Text>
                <Text style={base.bulletText}>{d}</Text>
              </View>
            ))}
          </View>
        )}

        {data.action_items.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Action Items</Text>
            {data.action_items.map((item, i) => (
              <View key={i} style={base.bullet}>
                <Text style={base.bulletDot}>→</Text>
                <Text style={[base.bulletText, { fontFamily: "Helvetica-Bold" }]}>{item}</Text>
              </View>
            ))}
          </View>
        )}

        {data.notable_quotes && data.notable_quotes.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Notable Quotes</Text>
            {data.notable_quotes.map((q, i) => (
              <View key={i} style={{ marginBottom: 10, paddingLeft: 10, borderLeftWidth: 2, borderLeftColor: GOLD }}>
                <Text style={{ fontSize: 10, fontFamily: "Helvetica-Oblique", color: BODY, lineHeight: 1.5 }}>
                  &ldquo;{q.quote}&rdquo;
                </Text>
                {q.speaker ? (
                  <Text style={{ fontSize: 9, color: MUTED, marginTop: 2 }}>— {q.speaker}</Text>
                ) : null}
              </View>
            ))}
          </View>
        )}

        <PageFooter />
      </Page>
    </Document>
  );
}

// ── KEY TAKEAWAYS ─────────────────────────────────────────────────────────────

export type KeyTakeawaysData = {
  format?: string;
  summary: string;
  takeaways: { headline: string; detail: string }[];
};

export function KeyTakeawaysPDFDocument({
  filename,
  data,
}: {
  filename: string;
  data: KeyTakeawaysData;
}) {
  return (
    <Document>
      <Page size="A4" style={base.page}>
        <View style={base.header}>
          <Text style={base.title}>{stripExt(filename)}</Text>
          <Text style={base.subtitle}>Key Takeaways  ·  {formatDate()}</Text>
          <Text style={base.subtitle}>Generated by CineFlow</Text>
        </View>

        {data.summary ? (
          <View>
            <Text style={base.sectionLabelFirst}>Context</Text>
            <Text style={{ fontSize: 10, fontFamily: "Helvetica-Oblique", color: MUTED, lineHeight: 1.6, marginBottom: 4 }}>
              {data.summary}
            </Text>
          </View>
        ) : null}

        <Text style={data.summary ? base.sectionLabel : base.sectionLabelFirst}>Key Takeaways</Text>

        {data.takeaways.map((t, i) => (
          <View key={i} style={{ marginBottom: 14 }}>
            <View style={{ flexDirection: "row", marginBottom: 4 }}>
              <Text style={{ width: 24, fontSize: 10, fontFamily: "Helvetica-Bold", color: GOLD }}>
                {String(i + 1).padStart(2, "0")}
              </Text>
              <Text style={{ flex: 1, fontSize: 11, fontFamily: "Helvetica-Bold", color: DARK, lineHeight: 1.4 }}>
                {t.headline}
              </Text>
            </View>
            <Text style={{ fontSize: 10, color: SUBTLE, lineHeight: 1.6, paddingLeft: 24 }}>
              {t.detail}
            </Text>
          </View>
        ))}

        <PageFooter />
      </Page>
    </Document>
  );
}

// ── CUT LIST ─────────────────────────────────────────────────────────────────

export type CutListData = {
  format: string;
  total_duration: string;
  cuts: {
    label: string;
    timecode_hint: string;
    quote: string;
    speaker?: string | null;
    note: string;
  }[];
  caption_suggestions?: string[];
  hook_options?: string[];
  editor_notes?: string;
  brief?: string;
};

const LABEL_COLORS_PDF: Record<string, string> = {
  "HOOK":           "#d4a853",
  "CORE MESSAGE":   "#60a5fa",
  "STORY BEAT":     "#38bdf8",
  "HUMOR BEAT":     "#facc15",
  "EMOTIONAL BEAT": "#a78bfa",
  "ENERGY HIT":     "#fb923c",
  "TRANSITION":     "#71717a",
  "CALLBACK":       "#f472b6",
  "CLOSE":          "#34d399",
  "OUTRO":          "#71717a",
};

export function CutListPDFDocument({
  filename,
  data,
}: {
  filename: string;
  data: CutListData;
}) {
  return (
    <Document>
      <Page size="A4" style={base.page}>
        <View style={base.header}>
          <Text style={base.title}>{stripExt(filename)}</Text>
          <Text style={base.subtitle}>{data.format}  ·  {formatDate()}</Text>
          <Text style={base.subtitle}>
            Generated by CineFlow  ·  Est. {data.total_duration}
            {data.brief ? `  ·  "${data.brief}"` : ""}
          </Text>
        </View>

        <Text style={base.sectionLabelFirst}>Cut List</Text>

        {data.cuts.map((cut, i) => {
          const labelColor = LABEL_COLORS_PDF[cut.label] ?? "#71717a";
          return (
            <View key={i} style={{ marginBottom: 12, paddingLeft: 10, borderLeftWidth: 2, borderLeftColor: labelColor }}>
              <View style={{ flexDirection: "row", marginBottom: 3 }}>
                <Text style={{ fontSize: 8, fontFamily: "Helvetica-Bold", color: labelColor, marginRight: 8 }}>
                  {cut.label}
                </Text>
                <Text style={{ fontSize: 8, color: MUTED, marginRight: 8 }}>{cut.timecode_hint}</Text>
                {cut.speaker ? (
                  <Text style={{ fontSize: 8, color: MUTED }}>— {cut.speaker}</Text>
                ) : null}
              </View>
              <Text style={{ fontSize: 10, fontFamily: "Helvetica-Oblique", color: BODY, lineHeight: 1.5, marginBottom: 3 }}>
                &ldquo;{cut.quote}&rdquo;
              </Text>
              <Text style={{ fontSize: 9, color: SUBTLE, lineHeight: 1.5 }}>{cut.note}</Text>
            </View>
          );
        })}

        {data.caption_suggestions && data.caption_suggestions.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Caption Suggestions</Text>
            {data.caption_suggestions.map((cap, i) => (
              <View key={i} style={base.bullet}>
                <Text style={base.bulletDot}>•</Text>
                <Text style={base.bulletText}>{cap}</Text>
              </View>
            ))}
          </View>
        )}

        {data.hook_options && data.hook_options.length > 0 && (
          <View>
            <Text style={base.sectionLabel}>Hook Options</Text>
            {data.hook_options.map((h, i) => (
              <View key={i} style={base.bullet}>
                <Text style={base.bulletDot}>{i + 1}.</Text>
                <Text style={base.bulletText}>{h}</Text>
              </View>
            ))}
          </View>
        )}

        {data.editor_notes ? (
          <View>
            <Text style={base.sectionLabel}>Editor Notes</Text>
            <Text style={[base.body, { color: SUBTLE }]}>{data.editor_notes}</Text>
          </View>
        ) : null}

        <PageFooter />
      </Page>
    </Document>
  );
}
