import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// ── Types ─────────────────────────────────────────────────────────────────────

export type ContractSection = { title: string; body: string };

export type ContractPDFData = {
  contractTitle: string;
  studioName: string;
  studioEmail?: string;
  recipientName: string;
  recipientEmail?: string;
  effectiveDate: string;
  sections: ContractSection[];
  templateLabel?: string;
};

// ── Styles ────────────────────────────────────────────────────────────────────

const GOLD   = "#d4a853";
const DARK   = "#0f0f0f";
const BODY   = "#1a1a1a";
const MUTED  = "#888888";
const SUBTLE = "#555555";
const BORDER = "#e5e5e5";

const s = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.6,
    color: BODY,
    paddingTop: 0,
    paddingBottom: 72,
    paddingHorizontal: 0,
    backgroundColor: "#ffffff",
  },
  // ── Header band ──
  headerBand: {
    backgroundColor: DARK,
    paddingHorizontal: 56,
    paddingTop: 40,
    paddingBottom: 32,
    marginBottom: 0,
  },
  headerMeta: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  headerTitle: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    color: "#ffffff",
    letterSpacing: -0.3,
    marginBottom: 2,
  },
  headerSub: {
    fontSize: 9,
    color: "#888888",
  },
  // ── Parties bar ──
  partiesBar: {
    flexDirection: "row",
    gap: 0,
    paddingHorizontal: 56,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
    backgroundColor: "#fafafa",
  },
  partyBlock: {
    flex: 1,
  },
  partyDivider: {
    width: 1,
    backgroundColor: BORDER,
    marginHorizontal: 24,
  },
  partyLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  partyName: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: DARK,
    marginBottom: 2,
  },
  partyEmail: {
    fontSize: 8.5,
    color: MUTED,
  },
  // ── Body ──
  body: {
    paddingHorizontal: 56,
    paddingTop: 28,
  },
  effectiveLine: {
    fontSize: 9,
    color: SUBTLE,
    marginBottom: 24,
    fontFamily: "Helvetica-Oblique",
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
    marginTop: 20,
  },
  sectionTitleFirst: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
    marginTop: 0,
  },
  sectionBody: {
    fontSize: 10,
    lineHeight: 1.7,
    color: BODY,
    marginBottom: 2,
  },
  divider: {
    height: 1,
    backgroundColor: BORDER,
    marginTop: 24,
    marginBottom: 0,
  },
  // ── Signature block ──
  sigBlock: {
    paddingHorizontal: 56,
    paddingTop: 24,
    paddingBottom: 16,
  },
  sigLabel: {
    fontSize: 7,
    fontFamily: "Helvetica-Bold",
    color: GOLD,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 16,
  },
  sigRow: {
    flexDirection: "row",
    gap: 0,
    marginBottom: 8,
  },
  sigParty: {
    flex: 1,
  },
  sigPartyRight: {
    flex: 1,
    paddingLeft: 32,
  },
  sigLine: {
    borderBottomWidth: 1,
    borderBottomColor: "#cccccc",
    marginBottom: 4,
    height: 32,
  },
  sigName: {
    fontSize: 8,
    color: MUTED,
  },
  sigRole: {
    fontSize: 7.5,
    color: "#aaaaaa",
    marginTop: 1,
  },
  // ── Footer ──
  footer: {
    position: "absolute",
    bottom: 24,
    left: 56,
    right: 56,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerLeft: {
    fontSize: 7.5,
    color: "#bbbbbb",
  },
  footerRight: {
    fontSize: 7.5,
    color: "#cccccc",
  },
});

// ── Footer component (fixed, appears on every page) ───────────────────────────

function PageFooter({ studioName }: { studioName: string }) {
  return (
    <View style={s.footer} fixed>
      <Text style={s.footerLeft}>
        {studioName} · Generated by Cineflow · Not legal advice — review with a licensed attorney
      </Text>
      <Text style={s.footerRight} render={({ pageNumber, totalPages }) =>
        `Page ${pageNumber} of ${totalPages}`
      } />
    </View>
  );
}

// ── Main document ─────────────────────────────────────────────────────────────

export function ContractPDFDocument({ data }: { data: ContractPDFData }) {
  const {
    contractTitle,
    studioName,
    studioEmail,
    recipientName,
    recipientEmail,
    effectiveDate,
    sections,
    templateLabel,
  } = data;

  return (
    <Document title={contractTitle} author={studioName}>
      <Page size="LETTER" style={s.page}>

        {/* ── Dark header ── */}
        <View style={s.headerBand}>
          {templateLabel && (
            <Text style={s.headerMeta}>{templateLabel}</Text>
          )}
          <Text style={s.headerTitle}>{contractTitle}</Text>
          <Text style={s.headerSub}>Effective {effectiveDate}</Text>
        </View>

        {/* ── Parties ── */}
        <View style={s.partiesBar}>
          <View style={s.partyBlock}>
            <Text style={s.partyLabel}>Studio / Service Provider</Text>
            <Text style={s.partyName}>{studioName}</Text>
            {studioEmail && <Text style={s.partyEmail}>{studioEmail}</Text>}
          </View>
          <View style={s.partyDivider} />
          <View style={s.partyBlock}>
            <Text style={s.partyLabel}>Client / Recipient</Text>
            <Text style={s.partyName}>{recipientName}</Text>
            {recipientEmail && <Text style={s.partyEmail}>{recipientEmail}</Text>}
          </View>
        </View>

        {/* ── Contract body ── */}
        <View style={s.body}>
          <Text style={s.effectiveLine}>
            This agreement is entered into as of {effectiveDate}, between {studioName} ("Studio") and {recipientName} ("Client").
          </Text>

          {sections.map((section, i) => (
            <View key={i}>
              <Text style={i === 0 ? s.sectionTitleFirst : s.sectionTitle}>
                {section.title}
              </Text>
              <Text style={s.sectionBody}>{section.body}</Text>
            </View>
          ))}
        </View>

        {/* ── Divider before sig block ── */}
        <View style={s.divider} />

        {/* ── Signature block ── */}
        <View style={s.sigBlock}>
          <Text style={s.sigLabel}>Signatures</Text>
          <View style={s.sigRow}>
            <View style={s.sigParty}>
              <View style={s.sigLine} />
              <Text style={s.sigName}>{studioName}</Text>
              <Text style={s.sigRole}>Studio / Service Provider</Text>
            </View>
            <View style={s.sigPartyRight}>
              <View style={s.sigLine} />
              <Text style={s.sigName}>{recipientName}</Text>
              <Text style={s.sigRole}>Client / Recipient</Text>
            </View>
          </View>
          <View style={[s.sigRow, { marginTop: 12 }]}>
            <View style={s.sigParty}>
              <View style={[s.sigLine, { height: 20 }]} />
              <Text style={s.sigName}>Date</Text>
            </View>
            <View style={s.sigPartyRight}>
              <View style={[s.sigLine, { height: 20 }]} />
              <Text style={s.sigName}>Date</Text>
            </View>
          </View>
        </View>

        <PageFooter studioName={studioName} />
      </Page>
    </Document>
  );
}
