import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    lineHeight: 1.6,
    color: "#1a1a1a",
    paddingTop: 56,
    paddingBottom: 56,
    paddingHorizontal: 60,
  },
  header: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    color: "#0f0f0f",
    marginBottom: 4,
  },
  meta: {
    fontSize: 9,
    color: "#888",
    marginTop: 2,
  },
  sectionLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#d4a853",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.7,
    color: "#1a1a1a",
  },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 60,
    right: 60,
    fontSize: 8,
    color: "#bbb",
    textAlign: "center",
  },
});

function formatDuration(secs: number): string {
  const m = Math.floor(secs / 60);
  const s = Math.round(secs % 60);
  return `${m}m ${s}s`;
}

export function TranscriptPDFDocument({
  text,
  filename,
  duration,
}: {
  text: string;
  filename: string;
  duration: number | null;
}) {
  const now = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{filename}</Text>
          <Text style={styles.meta}>
            Transcribed {now}{duration ? `  ·  Duration: ${formatDuration(duration)}` : ""}
          </Text>
          <Text style={styles.meta}>Generated by Cineflow</Text>
        </View>

        <Text style={styles.sectionLabel}>Transcript</Text>
        <Text style={styles.body}>{text}</Text>

        <Text style={styles.footer} render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        } fixed />
      </Page>
    </Document>
  );
}
